<?php

declare(strict_types=1);

return [
    'queue' => [
        'connection' => env('SCANNER_QUEUE_CONNECTION', 'redis'),
        'name' => env('SCANNER_QUEUE_NAME', 'scans'),
        'default_retry_limit' => (int) env('SCANNER_RETRY_LIMIT', 3),
        'default_timeout_seconds' => (int) env('SCANNER_TIMEOUT_SECONDS', 20),
    ],

    'confidence_levels' => ['high', 'mid', 'low'],

    'connector_cache_ttl_seconds' => (int) env('SCANNER_CONNECTOR_CACHE_TTL', 300),

    'performance' => [
        'dashboard_cache_ttl_seconds' => (int) env('SCANNER_DASHBOARD_CACHE_TTL', 30),
        'cancel_poll_every' => (int) env('SCANNER_CANCEL_POLL_EVERY', 5),
    ],

    // Phase B: all connectors are implemented as Laravel/PHP classes.
    'connectors' => [
        \App\Services\Scanning\Connectors\Generated\Username\CoderlegionUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\HackernewsUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\LemmyUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\StackoverflowUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\DevtoUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\GumroadUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\HashnodeUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\ItchIoUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\KaggleUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\MediumUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\PatreonUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\ProducthuntUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\SubstackUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\TwitchUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\BitbucketUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\CodebergUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\CratesioUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\DockerhubUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\GithubUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\GitlabUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\HuggingfaceUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\LaunchpadUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\LeetcodeUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\NpmjsUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\ReplitUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\SourceforgeUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\BuymeacoffeeUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\LiberapayUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\BattlenetUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\ChessComUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\LichessUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\MinecraftUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\MonkeytypeUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\OsuUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\RobloxUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\SteamUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\VintedUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\BlueskyUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\DiscordUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\InstagramUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\MastodonUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\PinterestUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\RedditUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\SnapchatUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\SoundcloudUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\TelegramUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\ThreadsUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\TiktokUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\XUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Username\YoutubeUsernameConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\BabestationEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\FlirtbateEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\MadePornEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\PornhubEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\SexvidEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\SuperpornEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\XnxxEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\XvideosEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\StackoverflowEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\AdobeEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\FlickrEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\GumroadEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\PatreonEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\CodecademyEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\CodepenEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\CodewarsEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\DevrantEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\EnvatoEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\GithubEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\HuggingfaceEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\LeetcodeEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\ReplitEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\SaashubEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\WixEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\WordpressEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\XdaEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\AppletvEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\JustwatchEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\LetterboxdEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\NetflixEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\StremioEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\AddictinggamesEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\ChessComEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\CrazygamesEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\UbisoftEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\RenderEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\FreelancerEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\AlisonEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\CourseraEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\DuolingoEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\SpotifyEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\AljazeeraEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\BbcEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\CnnEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\FoxnewsEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\GlobaltimesEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\IndiatimesEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\NytimesEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\EventbriteEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\MozEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\AxonautEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\HubspotEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\InsightlyEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\ZohoEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\FlipkartEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\NaturabuyEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\VivinoEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\WalmartEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\FacebookEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\InstagramEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\MastodonEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\PinterestEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\XEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\EspnEmailConnector::class,
        \App\Services\Scanning\Connectors\Generated\Email\MarcaEmailConnector::class,
    ],
];
