<?php

declare(strict_types=1);

namespace App\Services\Scanner;

final class MetadataBaselineValidationService
{
    public function __construct(
        private readonly MetadataAuditService $metadataAudit,
        private readonly MetadataCapabilityService $metadataCapability,
        private readonly ?string $registryPath = null,
    ) {
    }

    /**
     * @param array<int, string>|null $moduleKeys
     * @param array<string, mixed> $options
     * @return array<string, mixed>
     */
    public function validate(string $mode, ?array $moduleKeys = null, array $options = []): array
    {
        $registry = $this->baselineRegistry();
        $modules = $registry[$mode] ?? [];
        if ($moduleKeys !== null && $moduleKeys !== []) {
            $filter = array_fill_keys($moduleKeys, true);
            $modules = array_filter(
                $modules,
                static fn (mixed $targets, string $module): bool => isset($filter[$module]),
                ARRAY_FILTER_USE_BOTH
            );
        }

        $moduleReports = [];
        $overlay = [];
        foreach ($modules as $module => $targets) {
            if (!is_array($targets) || $targets === []) {
                continue;
            }

            $audit = $this->metadataAudit->audit($mode, array_values(array_map('strval', $targets)), null, [$module], $options);
            $summary = $this->summarizeModuleAudit($mode, (string) $module, $audit);
            $moduleReports[] = $summary;

            if ($summary['proposed_validated_level'] !== null) {
                $overlay[$module] = [
                    'validated_level' => $summary['proposed_validated_level'],
                    'validated_at' => $audit['generated_at'],
                    'targets' => $summary['successful_targets'],
                    'notes' => sprintf(
                        'Generated by scanner:metadata-validate-baselines from %d successful live validation target(s); conservative validated level is the minimum observed metadata level across successful targets.',
                        count($summary['successful_targets'])
                    ),
                ];
            }
        }

        usort($moduleReports, static fn (array $a, array $b): int => [$a['category'], $a['module']] <=> [$b['category'], $b['module']]);
        ksort($overlay);

        return [
            'generated_at' => now()->toIso8601String(),
            'mode' => $mode,
            'requested_modules' => array_values(array_keys($modules)),
            'summary' => $this->overallSummary($moduleReports),
            'modules' => $moduleReports,
            'proposed_validation_overlay' => [
                $mode => $overlay,
            ],
        ];
    }

    /**
     * @return array<string, array<string, array<int, string>>>
     */
    private function baselineRegistry(): array
    {
        $path = $this->registryPath ?? base_path('config/scanner_metadata_targets.php');
        if (!is_file($path)) {
            return [];
        }

        $loaded = require $path;

        return is_array($loaded) ? $loaded : [];
    }

    /**
     * @param array<string, mixed> $audit
     * @return array<string, mixed>
     */
    private function summarizeModuleAudit(string $mode, string $module, array $audit): array
    {
        $capability = $this->metadataCapability->forModule($mode, $module);
        $results = is_array($audit['results'] ?? null) ? $audit['results'] : [];
        $foundResults = array_values(array_filter(
            $results,
            static fn (array $result): bool => ($result['normalized_status'] ?? null) === 'found'
        ));
        $successfulTargets = array_values(array_unique(array_map(
            static fn (array $result): string => (string) $result['target'],
            $foundResults
        )));
        $failedTargets = array_values(array_unique(array_map(
            static fn (array $result): string => (string) $result['target'],
            array_filter(
                $results,
                static fn (array $result): bool => ($result['normalized_status'] ?? null) !== 'found'
            )
        )));

        $observedLevels = array_map(
            static fn (array $result): int => (int) ($result['observed_metadata_level'] ?? 0),
            $foundResults
        );
        $proposedLevel = $observedLevels === [] ? null : min($observedLevels);

        $statusBreakdown = [];
        foreach ($results as $result) {
            $status = (string) ($result['normalized_status'] ?? 'unknown');
            $statusBreakdown[$status] = ($statusBreakdown[$status] ?? 0) + 1;
        }
        ksort($statusBreakdown);

        return [
            'module' => $module,
            'category' => $capability['category'] ?? '',
            'documented_capability_level' => $capability['level'] ?? null,
            'documented_capability_strategy' => $capability['strategy'] ?? 'unknown',
            'current_validated_level' => $capability['validated_level'] ?? null,
            'current_validated_at' => $capability['validated_at'] ?? null,
            'current_validated_targets' => $capability['validated_targets'] ?? [],
            'proposed_validated_level' => $proposedLevel,
            'successful_targets' => $successfulTargets,
            'failed_targets' => $failedTargets,
            'status_breakdown' => $statusBreakdown,
            'audit_summary' => $audit['summary'] ?? [],
            'results' => $results,
        ];
    }

    /**
     * @param array<int, array<string, mixed>> $moduleReports
     * @return array<string, mixed>
     */
    private function overallSummary(array $moduleReports): array
    {
        $summary = [
            'modules_requested' => count($moduleReports),
            'modules_with_proposed_validation' => 0,
            'modules_below_documented_level' => 0,
            'successful_targets' => 0,
            'failed_targets' => 0,
        ];

        foreach ($moduleReports as $report) {
            if (($report['proposed_validated_level'] ?? null) !== null) {
                $summary['modules_with_proposed_validation']++;
            }
            if (
                $report['proposed_validated_level'] !== null
                && $report['documented_capability_level'] !== null
                && (int) $report['proposed_validated_level'] < (int) $report['documented_capability_level']
            ) {
                $summary['modules_below_documented_level']++;
            }

            $summary['successful_targets'] += count($report['successful_targets'] ?? []);
            $summary['failed_targets'] += count($report['failed_targets'] ?? []);
        }

        return $summary;
    }
}
