<?php

declare(strict_types=1);

namespace App\Services\Scanner;

final class MetadataBaselineValidationService
{
    public function __construct(
        private readonly MetadataAuditService $metadataAudit,
        private readonly MetadataCapabilityService $metadataCapability,
        private readonly MetadataTargetResolver $targetResolver,
        private readonly ?string $registryPath = null,
    ) {
    }

    /**
     * @param array<int, string>|null $moduleKeys
     * @param array<string, mixed> $options
     * @return array<string, mixed>
     */
    public function validate(string $mode, ?array $moduleKeys = null, array $options = []): array
    {
        $registry = $this->baselineRegistry();
        $modules = $registry[$mode] ?? [];
        if ($moduleKeys !== null && $moduleKeys !== []) {
            $filter = array_fill_keys($moduleKeys, true);
            $modules = array_filter(
                $modules,
                static fn (mixed $targets, string $module): bool => isset($filter[$module]),
                ARRAY_FILTER_USE_BOTH
            );
        }

        $moduleReports = [];
        $overlay = [];
        foreach ($modules as $module => $targets) {
            if (!is_array($targets) || $targets === []) {
                continue;
            }

            $resolvedTargets = $this->targetResolver->resolveMany($mode, array_values(array_map('strval', $targets)));
            $audit = $resolvedTargets['resolved'] === []
                ? self::emptyAudit($mode)
                : $this->metadataAudit->audit($mode, $resolvedTargets['resolved'], null, [$module], $options);
            $audit = self::aliasAuditTargets($audit, $resolvedTargets['labels_by_resolved'] ?? []);
            $summary = $this->summarizeModuleAudit($mode, (string) $module, $audit, $resolvedTargets['unresolved']);
            $moduleReports[] = $summary;

            if ($summary['proposed_validated_level'] !== null) {
                $overlay[$module] = [
                    'validated_level' => $summary['proposed_validated_level'],
                    'validated_at' => $audit['generated_at'],
                    'targets' => $summary['successful_targets'],
                    'notes' => sprintf(
                        'Generated by scanner:metadata-validate-baselines from %d successful live validation target(s); conservative validated level is the minimum observed metadata level across successful targets.',
                        count($summary['successful_targets'])
                    ),
                ];
            }
        }

        $moduleReports = self::sortModuleReports($moduleReports);
        ksort($overlay);

        return [
            'generated_at' => now()->toIso8601String(),
            'mode' => $mode,
            'requested_modules' => array_values(array_keys($modules)),
            'summary' => $this->overallSummary($moduleReports),
            'modules' => $moduleReports,
            'proposed_validation_overlay' => [
                $mode => $overlay,
            ],
        ];
    }

    /**
     * @return array<string, array<string, array<int, string>>>
     */
    private function baselineRegistry(): array
    {
        $path = $this->registryPath ?? base_path('config/scanner_metadata_targets.php');
        if (!is_file($path)) {
            return [];
        }

        $loaded = require $path;

        return is_array($loaded) ? $loaded : [];
    }

    /**
     * @param array<string, mixed> $audit
     * @return array<string, mixed>
     */
    private function summarizeModuleAudit(string $mode, string $module, array $audit, array $unresolvedTargets = []): array
    {
        $capability = $this->metadataCapability->forModule($mode, $module);
        $snapshot = self::auditSnapshot($audit, $unresolvedTargets);
        $proposedLevel = $snapshot['observed_levels'] === [] ? null : min($snapshot['observed_levels']);

        return [
            'module' => $module,
            'category' => $capability['category'] ?? '',
            'documented_capability_level' => $capability['level'] ?? null,
            'documented_capability_strategy' => $capability['strategy'] ?? 'unknown',
            'current_validated_level' => $capability['validated_level'] ?? null,
            'current_validated_at' => $capability['validated_at'] ?? null,
            'current_validated_targets' => $capability['validated_targets'] ?? [],
            'proposed_validated_level' => $proposedLevel,
            'validation_status' => $this->determineValidationStatus($snapshot['successful_targets'], $snapshot['failed_targets'], $snapshot['failed_results']),
            'successful_targets' => $snapshot['successful_targets'],
            'failed_targets' => $snapshot['failed_targets'],
            'status_breakdown' => $snapshot['status_breakdown'],
            'audit_summary' => $audit['summary'] ?? [],
            'results' => $snapshot['results'],
        ];
    }

    /**
     * @param array<int, array<string, mixed>> $moduleReports
     * @return array<string, mixed>
     */
    private function overallSummary(array $moduleReports): array
    {
        $summary = [
            'modules_requested' => count($moduleReports),
            'modules_with_proposed_validation' => 0,
            'modules_below_documented_level' => 0,
            'stable_modules' => 0,
            'partial_modules' => 0,
            'blocked_modules' => 0,
            'inconclusive_modules' => 0,
            'broken_modules' => 0,
            'successful_targets' => 0,
            'failed_targets' => 0,
        ];

        foreach ($moduleReports as $report) {
            if (($report['proposed_validated_level'] ?? null) !== null) {
                $summary['modules_with_proposed_validation']++;
            }
            if (
                $report['proposed_validated_level'] !== null
                && $report['documented_capability_level'] !== null
                && (int) $report['proposed_validated_level'] < (int) $report['documented_capability_level']
            ) {
                $summary['modules_below_documented_level']++;
            }

            $status = (string) ($report['validation_status'] ?? 'stable');
            if (isset($summary[$status . '_modules'])) {
                $summary[$status . '_modules']++;
            }

            $summary['successful_targets'] += count($report['successful_targets'] ?? []);
            $summary['failed_targets'] += count($report['failed_targets'] ?? []);
        }

        return $summary;
    }

    /**
     * @param array<int, string> $successfulTargets
     * @param array<int, string> $failedTargets
     * @param array<int, array<string, mixed>> $failedResults
     */
    private function determineValidationStatus(array $successfulTargets, array $failedTargets, array $failedResults): string
    {
        if ($successfulTargets !== []) {
            return $failedTargets === [] ? 'stable' : 'partial';
        }

        return self::classifyFailureSet($failedResults);
    }

    /**
     * @return array<string, mixed>
     */
    public static function emptyAudit(string $mode): array
    {
        return [
            'generated_at' => now()->toIso8601String(),
            'mode' => $mode,
            'summary' => [
                'audited_results' => 0,
                'found_results' => 0,
                'not_found_results' => 0,
                'error_results' => 0,
                'results_with_metadata_level_3_plus' => 0,
                'results_with_metadata_level_4' => 0,
                'found_results_below_documented_level' => 0,
            ],
            'results' => [],
        ];
    }

    /**
     * @param array<string, mixed> $audit
     * @param array<string, string> $labelsByResolved
     * @return array<string, mixed>
     */
    public static function aliasAuditTargets(array $audit, array $labelsByResolved): array
    {
        if ($labelsByResolved === []) {
            return $audit;
        }

        $audit['targets'] = array_values(array_map(
            fn (string $target): string => $labelsByResolved[$target] ?? $target,
            array_values(array_map('strval', is_array($audit['targets'] ?? null) ? $audit['targets'] : [])),
        ));

        $audit['plans'] = array_map(function (mixed $plan) use ($labelsByResolved): mixed {
            if (!is_array($plan)) {
                return $plan;
            }

            if (is_string($plan['target'] ?? null)) {
                $plan['target'] = $labelsByResolved[$plan['target']] ?? $plan['target'];
            }

            if (is_array($plan['expanded_targets'] ?? null)) {
                $plan['expanded_targets'] = array_values(array_map(
                    fn (string $target): string => $labelsByResolved[$target] ?? $target,
                    array_values(array_map('strval', $plan['expanded_targets'])),
                ));
            }

            return $plan;
        }, is_array($audit['plans'] ?? null) ? $audit['plans'] : []);

        $audit['results'] = array_map(function (mixed $result) use ($labelsByResolved): mixed {
            if (!is_array($result)) {
                return $result;
            }

            if (is_string($result['target'] ?? null)) {
                $result['target'] = $labelsByResolved[$result['target']] ?? $result['target'];
            }

            if (is_array($result['normalized'] ?? null) && is_string($result['normalized']['target'] ?? null)) {
                $result['normalized']['target'] = $labelsByResolved[$result['normalized']['target']] ?? $result['normalized']['target'];
            }

            return $result;
        }, is_array($audit['results'] ?? null) ? $audit['results'] : []);

        return $audit;
    }

    /**
     * @param array<string, mixed> $audit
     * @param array<int, string> $unresolvedTargets
     * @return array{
     *   results: array<int, array<string, mixed>>,
     *   successful_targets: array<int, string>,
     *   failed_targets: array<int, string>,
     *   failed_results: array<int, array<string, mixed>>,
     *   observed_levels: array<int, int>,
     *   status_breakdown: array<string, int>
     * }
     */
    public static function auditSnapshot(array $audit, array $unresolvedTargets = []): array
    {
        $results = array_values(array_filter(
            is_array($audit['results'] ?? null) ? $audit['results'] : [],
            static fn (mixed $result): bool => is_array($result),
        ));

        $foundResults = array_values(array_filter(
            $results,
            static fn (array $result): bool => ($result['normalized_status'] ?? null) === 'found'
        ));

        $successfulTargets = array_values(array_unique(array_map(
            static fn (array $result): string => (string) ($result['target'] ?? ''),
            $foundResults
        )));

        $failedResults = array_values(array_filter(
            $results,
            static fn (array $result): bool => ($result['normalized_status'] ?? null) !== 'found'
        ));

        $failedTargets = array_values(array_unique(array_map(
            static fn (array $result): string => (string) ($result['target'] ?? ''),
            $failedResults
        )));
        $failedTargets = array_values(array_unique(array_merge(
            $failedTargets,
            array_values(array_map('strval', $unresolvedTargets)),
        )));

        $observedLevels = array_map(
            static fn (array $result): int => (int) ($result['observed_metadata_level'] ?? 0),
            $foundResults
        );

        $statusBreakdown = [];
        foreach ($results as $result) {
            $status = (string) ($result['normalized_status'] ?? 'unknown');
            $statusBreakdown[$status] = ($statusBreakdown[$status] ?? 0) + 1;
        }
        ksort($statusBreakdown);

        return [
            'results' => $results,
            'successful_targets' => $successfulTargets,
            'failed_targets' => $failedTargets,
            'failed_results' => $failedResults,
            'observed_levels' => $observedLevels,
            'status_breakdown' => $statusBreakdown,
        ];
    }

    /**
     * @param array<int, array<string, mixed>> $failedResults
     */
    public static function classifyFailureSet(array $failedResults): string
    {
        if (self::isInconclusiveFailureSet($failedResults)) {
            return 'inconclusive';
        }

        if (self::isBlockedFailureSet($failedResults)) {
            return 'blocked';
        }

        return 'broken';
    }

    /**
     * @param array<int, array<string, mixed>> $moduleReports
     * @return array<int, array<string, mixed>>
     */
    public static function sortModuleReports(array $moduleReports): array
    {
        usort($moduleReports, static fn (array $a, array $b): int => [$a['category'], $a['module']] <=> [$b['category'], $b['module']]);

        return $moduleReports;
    }

    /**
     * @param array<int, array<string, mixed>> $failedResults
     */
    private static function isInconclusiveFailureSet(array $failedResults): bool
    {
        if ($failedResults === []) {
            return false;
        }

        foreach ($failedResults as $result) {
            if (($result['normalized_status'] ?? null) !== 'error') {
                return false;
            }

            $statusDetail = (string) ($result['status_detail'] ?? '');
            if (!in_array($statusDetail, ['network_error', 'tls_blocked'], true)) {
                return false;
            }
        }

        return true;
    }

    /**
     * @param array<int, array<string, mixed>> $failedResults
     */
    private static function isBlockedFailureSet(array $failedResults): bool
    {
        if ($failedResults === []) {
            return false;
        }

        foreach ($failedResults as $result) {
            if (($result['normalized_status'] ?? null) !== 'error') {
                return false;
            }

            $statusDetail = (string) ($result['status_detail'] ?? '');
            if (!in_array($statusDetail, ['anti_bot', 'blocked', 'rate_limited'], true)) {
                return false;
            }
        }

        return true;
    }
}
