<?php

return [
    'username' => [
        'venmo' => [
            'level' => 4,
            'category' => 'social',
            'path' => 'app/Services/Scanner/Validators/Generated/Manual/User/VenmoValidator.php',
            'strategy' => 'laravel-public-api-enrichment',
            'notes' => 'Private Laravel validator uses Venmo\'s public user endpoint to return direct profile identity metadata such as display name, bio, avatar, join date, account type, and durable public profile evidence.',
        ],
    ],
    'email' => [
        'adobe' => [
            'level' => 4,
            'strategy' => 'laravel-auth-metadata-enrichment',
            'notes' => 'Laravel email validator returns structured authentication-method and account-type metadata from Adobe account evidence.',
        ],
        'allen' => [
            'level' => 4,
            'strategy' => 'laravel-identity-evidence-enrichment',
            'notes' => 'Laravel email validator returns structured identity metadata from Allen pre-login identity evidence.',
        ],
        'appletv' => [
            'level' => 4,
            'strategy' => 'laravel-federated-account-enrichment',
            'notes' => 'Laravel email validator returns Apple TV account-existence metadata plus display name and sign-in option evidence from the federate endpoint.',
        ],
        'bible' => [
            'level' => 4,
            'category' => 'community',
            'path' => 'app/Services/Scanner/Validators/Email/BibleEmailValidator.php',
            'strategy' => 'public-evidence-pivot',
            'notes' => 'Private Laravel validator confirms Bible profiles only when public Gravatar evidence links the email to a public Bible profile URL, then extracts richer public hydration metadata such as user ID and avatar when exposed.',
        ],
        'coursera' => [
            'level' => 4,
            'strategy' => 'laravel-login-method-enrichment',
            'notes' => 'Laravel email validator returns structured account-existence and login-method evidence with diagnostics for registered Coursera accounts.',
        ],
        'doordash' => [
            'level' => 0,
            'category' => 'other',
            'path' => 'app/Services/Scanner/Validators/Email/DoordashEmailValidator.php',
            'strategy' => 'safety-blocked-placeholder',
            'notes' => 'Private Laravel validator is intentionally skipped until phone or social recovery hints can be gathered without notification or recovery side effects.',
        ],
        'dropbox' => [
            'level' => 0,
            'category' => 'hosting',
            'path' => 'app/Services/Scanner/Validators/Email/DropboxEmailValidator.php',
            'strategy' => 'safety-blocked-placeholder',
            'notes' => 'Private Laravel validator is intentionally skipped until passkey hints can be gathered safely from an unauthenticated flow.',
        ],
        'duolingo' => [
            'level' => 4,
            'strategy' => 'laravel-public-profile-enrichment',
            'notes' => 'Laravel email validator returns direct profile URL, avatar, account identifiers, and activity signals from the public Duolingo users API.',
        ],
        'etsy' => [
            'level' => 4,
            'strategy' => 'laravel-account-evidence-enrichment',
            'notes' => 'Laravel email validator returns rich Etsy profile, seller, privacy, and stats metadata for registered accounts.',
        ],
        'eventbrite' => [
            'level' => 4,
            'strategy' => 'laravel-account-lookup-enrichment',
            'notes' => 'Laravel email validator returns structured Eventbrite account evidence, sign-in methods, organizer status, and MFA hints.',
        ],
        'foursquare' => [
            'level' => 4,
            'category' => 'social',
            'path' => 'app/Services/Scanner/Validators/Email/FoursquareEmailValidator.php',
            'strategy' => 'public-evidence-pivot',
            'notes' => 'Private Laravel validator confirms Foursquare profiles only when public Gravatar evidence links the email to a public profile URL, then extracts richer public hydration metadata when available.',
        ],
        'github' => [
            'level' => 4,
            'strategy' => 'laravel-public-evidence-account-enrichment',
            'notes' => 'Laravel email validator combines GitHub signup account evidence with public Gravatar-linked GitHub profile enrichment when attribution is defensible.',
        ],
        'gitlab' => [
            'level' => 4,
            'category' => 'dev',
            'path' => 'app/Services/Scanner/Validators/Email/GitlabEmailValidator.php',
            'strategy' => 'public-evidence-pivot',
            'notes' => 'Private Laravel validator only confirms GitLab profiles when public Gravatar evidence links the email to a public GitLab profile and API record.',
        ],
        'gmail' => [
            'level' => 0,
            'category' => 'other',
            'path' => 'app/Services/Scanner/Validators/Email/GmailEmailValidator.php',
            'strategy' => 'safety-blocked-placeholder',
            'notes' => 'Private Laravel validator is intentionally skipped because safe non-notifying Gmail account evidence is not yet validated.',
        ],
        'gravatar' => [
            'level' => 4,
            'category' => 'social',
            'path' => 'app/Services/Scanner/Validators/Email/GravatarEmailValidator.php',
            'strategy' => 'public-profile-pivot',
            'notes' => 'Private Laravel validator returns direct public Gravatar profile metadata, hashes, avatar, links, and public profile URL.',
        ],
        'indiatimes' => [
            'level' => 4,
            'strategy' => 'laravel-verification-state-enrichment',
            'notes' => 'Laravel email validator returns structured account-existence and email-verification metadata with diagnostics from Indiatimes account evidence.',
        ],
        'libravatar' => [
            'level' => 3,
            'category' => 'social',
            'path' => 'app/Services/Scanner/Validators/Email/LibravatarEmailValidator.php',
            'strategy' => 'avatar-evidence-pivot',
            'notes' => 'Private Laravel validator returns public avatar evidence, hashes, and source attribution from Libravatar without touching login or recovery flows.',
        ],
        'otter' => [
            'level' => 4,
            'category' => 'other',
            'path' => 'app/Services/Scanner/Validators/Generated/Manual/Email/OtterEmailValidator.php',
            'strategy' => 'laravel-signed-prelogin-workspace-enrichment',
            'notes' => 'Private Laravel validator bootstraps Otter\'s pre-login CSRF session and uses the signed multipart check_email flow to return account existence, email verification, provider/domain, and workspace SSO metadata without touching recovery flows.',
        ],
        'pandora' => [
            'level' => 0,
            'category' => 'music',
            'path' => 'app/Services/Scanner/Validators/Email/PandoraEmailValidator.php',
            'strategy' => 'safety-blocked-placeholder',
            'notes' => 'Private Laravel validator is intentionally skipped until a non-notifying unauthenticated metadata path is validated.',
        ],
        'plex' => [
            'level' => 3,
            'category' => 'entertainment',
            'path' => 'app/Services/Scanner/Validators/Email/PlexEmailValidator.php',
            'strategy' => 'public-evidence-pivot',
            'notes' => 'Private Laravel validator only confirms Plex-related public profiles when public Gravatar evidence links the email to a public profile URL.',
        ],
        'ripe' => [
            'level' => 0,
            'category' => 'other',
            'path' => 'app/Services/Scanner/Validators/Email/RipeEmailValidator.php',
            'strategy' => 'safety-blocked-placeholder',
            'notes' => 'Private Laravel validator is intentionally skipped until phone-hint extraction can be proven safe and non-notifying.',
        ],
        'samsclub' => [
            'level' => 4,
            'category' => 'shopping',
            'path' => 'app/Services/Scanner/Validators/Email/SamsclubEmailValidator.php',
            'strategy' => 'laravel-direct-auth-enrichment',
            'notes' => 'Private Laravel validator bootstraps the public SamsClub identity session and reads direct GetLoginOptions metadata such as sign-in preference, masked contact hints, and passkey capability without triggering OTP delivery.',
        ],
        'smule' => [
            'level' => 4,
            'category' => 'music',
            'path' => 'app/Services/Scanner/Validators/Email/SmuleEmailValidator.php',
            'strategy' => 'public-evidence-pivot',
            'notes' => 'Private Laravel validator confirms Smule profiles only when public Gravatar evidence links the email to a public profile URL, then extracts richer public hydration metadata such as user ID, JID, and verification type when exposed.',
        ],
        'typeform' => [
            'level' => 0,
            'category' => 'other',
            'path' => 'app/Services/Scanner/Validators/Email/TypeformEmailValidator.php',
            'strategy' => 'safety-blocked-placeholder',
            'notes' => 'Private Laravel validator is intentionally skipped until password and SSO hints can be validated safely.',
        ],
        'unavatar' => [
            'level' => 3,
            'category' => 'social',
            'path' => 'app/Services/Scanner/Validators/Email/UnavatarEmailValidator.php',
            'strategy' => 'avatar-evidence-pivot',
            'notes' => 'Private Laravel validator returns public avatar evidence, hashes, and inferred source attribution from Unavatar without touching login or recovery flows.',
        ],
        'vedantu' => [
            'level' => 4,
            'strategy' => 'laravel-phone-evidence-enrichment',
            'notes' => 'Laravel email validator returns structured phone evidence from Vedantu pre-login account checks.',
        ],
        'vivino' => [
            'level' => 4,
            'strategy' => 'laravel-account-state-enrichment',
            'notes' => 'Laravel email validator returns structured account-existence and Vivino account-state metadata with diagnostics for registered accounts.',
        ],
        'vsco' => [
            'level' => 3,
            'category' => 'creator',
            'path' => 'app/Services/Scanner/Validators/Email/VscoEmailValidator.php',
            'strategy' => 'public-evidence-pivot',
            'notes' => 'Private Laravel validator only confirms VSCO profiles when public Gravatar evidence links the email to a public profile URL.',
        ],
        'walmart' => [
            'level' => 4,
            'strategy' => 'laravel-account-preference-enrichment',
            'notes' => 'Laravel email validator returns structured sign-in preference, masked contact, passkey, and residency metadata from Walmart account evidence.',
        ],
        'wanderlog' => [
            'level' => 4,
            'category' => 'travel',
            'path' => 'app/Services/Scanner/Validators/Email/WanderlogEmailValidator.php',
            'strategy' => 'public-evidence-pivot',
            'notes' => 'Private Laravel validator confirms Wanderlog profiles only when public Gravatar evidence links the email to a public profile URL, then extracts richer public hydration metadata when available.',
        ],
        'wix' => [
            'level' => 4,
            'strategy' => 'laravel-account-provider-enrichment',
            'notes' => 'Laravel email validator returns structured provider and account-type metadata for registered Wix accounts.',
        ],
    ],
];
