<?php

declare(strict_types=1);

namespace Tests\Unit;

use App\Services\Scanner\MetadataCapabilityService;
use Tests\TestCase;

final class MetadataCapabilityInventoryTest extends TestCase
{
    public function test_metadata_capability_inventory_documents_active_june_modules(): void
    {
        $summary = app(MetadataCapabilityService::class)->summary();

        $this->assertGreaterThanOrEqual(250, $summary['documented_modules']);
        $this->assertGreaterThanOrEqual(150, $summary['level_3_plus']);
        $this->assertGreaterThanOrEqual(50, $summary['level_4']);
        $this->assertGreaterThanOrEqual(50, $summary['validated_modules']);
        $this->assertGreaterThanOrEqual(50, $summary['validated_levels']['level_4']);
    }

    public function test_inventory_contains_known_modules_with_expected_capability_classes(): void
    {
        $service = app(MetadataCapabilityService::class);

        $thirtyFivePhoto = $service->forModule('username', '35photo');
        $aboutMe = $service->forModule('username', 'about_me');
        $atcoder = $service->forModule('username', 'atcoder');
        $arduino = $service->forModule('username', 'arduino');
        $anilist = $service->forModule('username', 'anilist');
        $archwiki = $service->forModule('username', 'archwiki');
        $asciinema = $service->forModule('username', 'asciinema');
        $bandlab = $service->forModule('username', 'bandlab');
        $behance = $service->forModule('username', 'behance');
        $beatstars = $service->forModule('username', 'beatstars');
        $blogger = $service->forModule('username', 'blogger');
        $bluesky = $service->forModule('username', 'bluesky');
        $boosty = $service->forModule('username', 'boosty');
        $bootDev = $service->forModule('username', 'boot_dev');
        $buyMeACoffee = $service->forModule('username', 'buymeacoffee');
        $calendly = $service->forModule('username', 'calendly');
        $chessCom = $service->forModule('username', 'chess_com');
        $codecademy = $service->forModule('username', 'codecademy');
        $codewars = $service->forModule('username', 'codewars');
        $codeberg = $service->forModule('username', 'codeberg');
        $codeforces = $service->forModule('username', 'codeforces');
        $coderwall = $service->forModule('username', 'coderwall');
        $cratesio = $service->forModule('username', 'cratesio');
        $dailymotion = $service->forModule('username', 'dailymotion');
        $dailyDev = $service->forModule('username', 'daily_dev');
        $deviantart = $service->forModule('username', 'deviantart');
        $devto = $service->forModule('username', 'devto');
        $discogs = $service->forModule('username', 'discogs');
        $discourseMeta = $service->forModule('username', 'discourse_meta');
        $disqus = $service->forModule('username', 'disqus');
        $donatealerts = $service->forModule('username', 'donatealerts');
        $dribbble = $service->forModule('username', 'dribbble');
        $dockerhub = $service->forModule('username', 'dockerhub');
        $duolingo = $service->forModule('username', 'duolingo');
        $etoro = $service->forModule('username', 'etoro');
        $flickr = $service->forModule('username', 'flickr');
        $freesound = $service->forModule('username', 'freesound');
        $freelancer = $service->forModule('username', 'freelancer');
        $github = $service->forModule('username', 'github');
        $ghostForum = $service->forModule('username', 'ghost_forum');
        $gitea = $service->forModule('username', 'gitea');
        $githubgist = $service->forModule('username', 'githubgist');
        $gitlab = $service->forModule('username', 'gitlab');
        $gravatar = $service->forModule('username', 'gravatar');
        $gumroad = $service->forModule('username', 'gumroad');
        $gpodderNet = $service->forModule('username', 'gpodder_net');
        $hackerrank = $service->forModule('username', 'hackerrank');
        $habr = $service->forModule('username', 'habr');
        $hashicorpDiscuss = $service->forModule('username', 'hashicorp_discuss');
        $hackernews = $service->forModule('username', 'hackernews');
        $hashnode = $service->forModule('username', 'hashnode');
        $huggingface = $service->forModule('username', 'huggingface');
        $imgur = $service->forModule('username', 'imgur');
        $instructables = $service->forModule('username', 'instructables');
        $ifttt = $service->forModule('username', 'ifttt');
        $itchIo = $service->forModule('username', 'itch_io');
        $jupyterForum = $service->forModule('username', 'jupyter_forum');
        $etsy = $service->forModule('email', 'etsy');
        $vivinoEmail = $service->forModule('email', 'vivino');
        $kaggle = $service->forModule('username', 'kaggle');
        $keybase = $service->forModule('username', 'keybase');
        $kotlinDiscuss = $service->forModule('username', 'kotlin_discuss');
        $leetcode = $service->forModule('username', 'leetcode');
        $lichess = $service->forModule('username', 'lichess');
        $linktree = $service->forModule('username', 'linktree');
        $launchpad = $service->forModule('username', 'launchpad');
        $lastfm = $service->forModule('username', 'lastfm');
        $livejournal = $service->forModule('username', 'livejournal');
        $mastodon = $service->forModule('username', 'mastodon');
        $minds = $service->forModule('username', 'minds');
        $minecraft = $service->forModule('username', 'minecraft');
        $mixcloud = $service->forModule('username', 'mixcloud');
        $monkeytype = $service->forModule('username', 'monkeytype');
        $niftygateway = $service->forModule('username', 'niftygateway');
        $naturalnews = $service->forModule('username', 'naturalnews');
        $mozillaDiscourse = $service->forModule('username', 'mozilladiscourse');
        $omglol = $service->forModule('username', 'omglol');
        $operaforums = $service->forModule('username', 'operaforums');
        $osu = $service->forModule('username', 'osu');
        $openstreetmap = $service->forModule('username', 'openstreetmap');
        $patreon = $service->forModule('username', 'patreon');
        $pinterest = $service->forModule('username', 'pinterest');
        $wix = $service->forModule('email', 'wix');
        $packagist = $service->forModule('username', 'packagist');
        $paragraph = $service->forModule('username', 'paragraph');
        $pastebin = $service->forModule('username', 'pastebin');
        $picsart = $service->forModule('username', 'picsart');
        $pypi = $service->forModule('username', 'pypi');
        $pythonDiscuss = $service->forModule('username', 'python_discuss');
        $snapchat = $service->forModule('username', 'snapchat');
        $speedrun = $service->forModule('username', 'speedrun');
        $rustUsers = $service->forModule('username', 'rust_users');
        $scratch = $service->forModule('username', 'scratch');
        $sourceforge = $service->forModule('username', 'sourceforge');
        $stackoverflow = $service->forModule('username', 'stackoverflow');
        $substack = $service->forModule('username', 'substack');
        $sportstracker = $service->forModule('username', 'sportstracker');
        $statsfm = $service->forModule('username', 'statsfm');
        $steam = $service->forModule('username', 'steam');
        $telegram = $service->forModule('username', 'telegram');
        $soundcloud = $service->forModule('username', 'soundcloud');
        $spotify = $service->forModule('username', 'spotify');
        $trello = $service->forModule('username', 'trello');
        $vimeo = $service->forModule('username', 'vimeo');
        $vivino = $service->forModule('username', 'vivino');
        $warpcast = $service->forModule('username', 'warpcast');
        $weebly = $service->forModule('username', 'weebly');
        $wikipedia = $service->forModule('username', 'wikipedia');
        $wordpress = $service->forModule('username', 'wordpress');
        $x = $service->forModule('username', 'x');
        $youtube = $service->forModule('username', 'youtube');

        $this->assertNotNull($arduino);
        $this->assertNotNull($archwiki);
        $this->assertNotNull($asciinema);
        $this->assertNotNull($bandlab);
        $this->assertNotNull($behance);
        $this->assertNotNull($beatstars);
        $this->assertNotNull($blogger);
        $this->assertNotNull($bluesky);
        $this->assertNotNull($boosty);
        $this->assertNotNull($bootDev);
        $this->assertNotNull($buyMeACoffee);
        $this->assertNotNull($calendly);
        $this->assertNotNull($chessCom);
        $this->assertNotNull($codecademy);
        $this->assertNotNull($codewars);
        $this->assertNotNull($codeberg);
        $this->assertNotNull($codeforces);
        $this->assertNotNull($coderwall);
        $this->assertNotNull($cratesio);
        $this->assertNotNull($dailymotion);
        $this->assertNotNull($dailyDev);
        $this->assertNotNull($deviantart);
        $this->assertNotNull($devto);
        $this->assertNotNull($discogs);
        $this->assertNotNull($discourseMeta);
        $this->assertNotNull($disqus);
        $this->assertNotNull($donatealerts);
        $this->assertNotNull($dribbble);
        $this->assertNotNull($dockerhub);
        $this->assertNotNull($duolingo);
        $this->assertNotNull($flickr);
        $this->assertNotNull($freelancer);
        $this->assertNotNull($github);
        $this->assertNotNull($ghostForum);
        $this->assertNotNull($gitea);
        $this->assertNotNull($githubgist);
        $this->assertNotNull($gitlab);
        $this->assertNotNull($gravatar);
        $this->assertNotNull($gumroad);
        $this->assertNotNull($gpodderNet);
        $this->assertNotNull($hackerrank);
        $this->assertNotNull($habr);
        $this->assertNotNull($hashicorpDiscuss);
        $this->assertNotNull($hackernews);
        $this->assertNotNull($hashnode);
        $this->assertNotNull($huggingface);
        $this->assertNotNull($imgur);
        $this->assertNotNull($instructables);
        $this->assertNotNull($ifttt);
        $this->assertNotNull($itchIo);
        $this->assertNotNull($jupyterForum);
        $this->assertNotNull($etsy);
        $this->assertNotNull($vivinoEmail);
        $this->assertNotNull($kaggle);
        $this->assertNotNull($keybase);
        $this->assertNotNull($kotlinDiscuss);
        $this->assertNotNull($leetcode);
        $this->assertNotNull($lichess);
        $this->assertNotNull($linktree);
        $this->assertNotNull($launchpad);
        $this->assertNotNull($lastfm);
        $this->assertNotNull($livejournal);
        $this->assertNotNull($mastodon);
        $this->assertNotNull($minecraft);
        $this->assertNotNull($mixcloud);
        $this->assertNotNull($niftygateway);
        $this->assertNotNull($mozillaDiscourse);
        $this->assertNotNull($omglol);
        $this->assertNotNull($operaforums);
        $this->assertNotNull($osu);
        $this->assertNotNull($openstreetmap);
        $this->assertNotNull($patreon);
        $this->assertNotNull($pinterest);
        $this->assertNotNull($wix);
        $this->assertNotNull($packagist);
        $this->assertNotNull($paragraph);
        $this->assertNotNull($pastebin);
        $this->assertNotNull($picsart);
        $this->assertNotNull($pythonDiscuss);
        $this->assertNotNull($snapchat);
        $rubygems = $service->forModule('username', 'rubygems');
        $this->assertNotNull($rustUsers);
        $this->assertNotNull($scratch);
        $this->assertNotNull($sourceforge);
        $this->assertNotNull($speedrun);
        $this->assertNotNull($statsfm);
        $this->assertNotNull($steam);
        $this->assertNotNull($soundcloud);
        $this->assertNotNull($spotify);
        $this->assertNotNull($substack);
        $this->assertNotNull($telegram);
        $this->assertNotNull($trello);
        $this->assertNotNull($vimeo);
        $this->assertNotNull($vivino);
        $this->assertNotNull($warpcast);
        $warframemarket = $service->forModule('username', 'warframemarket');
        $this->assertNotNull($weebly);
        $this->assertNotNull($wikipedia);
        $this->assertNotNull($wordpress);
        $this->assertNotNull($youtube);
        $this->assertNotNull($rubygems);
        $this->assertNotNull($thirtyFivePhoto);
        $this->assertNotNull($aboutMe);
        $this->assertNotNull($atcoder);
        $this->assertSame(4, $arduino['validated_level']);
        $this->assertSame(['arduino'], $arduino['validated_targets']);
        $this->assertNotNull($anilist);
        $this->assertSame(4, $archwiki['validated_level']);
        $this->assertSame(['Alad'], $archwiki['validated_targets']);
        $this->assertSame(3, $asciinema['validated_level']);
        $this->assertSame(['asciinema'], $asciinema['validated_targets']);
        $this->assertSame(4, $thirtyFivePhoto['validated_level']);
        $this->assertSame(['35photo'], $thirtyFivePhoto['validated_targets']);
        $this->assertSame(3, $aboutMe['validated_level']);
        $this->assertSame(['aboutme'], $aboutMe['validated_targets']);
        $this->assertSame(4, $atcoder['validated_level']);
        $this->assertSame(['chokudai'], $atcoder['validated_targets']);
        $this->assertSame(3, $anilist['validated_level']);
        $this->assertSame(['anilist'], $anilist['validated_targets']);
        $this->assertSame(4, $bandlab['validated_level']);
        $this->assertSame(['bandlab'], $bandlab['validated_targets']);
        $this->assertSame(4, $behance['validated_level']);
        $this->assertSame(['behanceprofile'], $behance['validated_targets']);
        $this->assertSame(4, $beatstars['validated_level']);
        $this->assertSame(['beatstars'], $beatstars['validated_targets']);
        $this->assertSame(4, $blogger['validated_level']);
        $this->assertSame(['googleblog'], $blogger['validated_targets']);
        $this->assertSame(3, $bluesky['validated_level']);
        $this->assertSame(['bluesky'], $bluesky['validated_targets']);
        $this->assertSame(4, $boosty['validated_level']);
        $this->assertSame(['boosty'], $boosty['validated_targets']);
        $this->assertSame(4, $bootDev['validated_level']);
        $this->assertSame(['bootdev'], $bootDev['validated_targets']);
        $this->assertSame(4, $buyMeACoffee['validated_level']);
        $this->assertSame(['pickacountry'], $buyMeACoffee['validated_targets']);
        $this->assertSame(4, $calendly['validated_level']);
        $this->assertSame(['calendly'], $calendly['validated_targets']);
        $this->assertSame(4, $chessCom['validated_level']);
        $this->assertSame(['hikaru'], $chessCom['validated_targets']);
        $this->assertSame(4, $codecademy['validated_level']);
        $this->assertSame(['codecademy'], $codecademy['validated_targets']);
        $this->assertSame(4, $codewars['validated_level']);
        $this->assertSame(['g964'], $codewars['validated_targets']);
        $this->assertSame(4, $codeberg['validated_level']);
        $this->assertSame(['codeberg'], $codeberg['validated_targets']);
        $this->assertSame(4, $codeforces['validated_level']);
        $this->assertSame(['codeforces'], $codeforces['validated_targets']);
        $this->assertSame(4, $coderwall['validated_level']);
        $this->assertSame(['coderwall'], $coderwall['validated_targets']);
        $this->assertSame(4, $cratesio['validated_level']);
        $this->assertSame(['alexcrichton'], $cratesio['validated_targets']);
        $this->assertSame(4, $dailymotion['validated_level']);
        $this->assertSame(['dailymotion'], $dailymotion['validated_targets']);
        $this->assertSame(4, $dailyDev['validated_level']);
        $this->assertSame(['dailydotdev'], $dailyDev['validated_targets']);
        $this->assertSame(4, $deviantart['validated_level']);
        $this->assertSame(['deviantart'], $deviantart['validated_targets']);
        $this->assertSame(4, $devto['validated_level']);
        $this->assertContains('ben', $devto['validated_targets']);
        $this->assertSame(4, $discogs['validated_level']);
        $this->assertSame(['discogs'], $discogs['validated_targets']);
        $this->assertSame(4, $discourseMeta['validated_level']);
        $this->assertSame(['sam'], $discourseMeta['validated_targets']);
        $this->assertSame(3, $disqus['validated_level']);
        $this->assertSame(['disqus'], $disqus['validated_targets']);
        $this->assertSame(4, $donatealerts['validated_level']);
        $this->assertSame(['donationalerts'], $donatealerts['validated_targets']);
        $this->assertSame(4, $dribbble['validated_level']);
        $this->assertContains('desandro', $dribbble['validated_targets']);
        $this->assertSame(4, $dockerhub['validated_level']);
        $this->assertSame(['docker'], $dockerhub['validated_targets']);
        $this->assertSame(4, $duolingo['validated_level']);
        $this->assertSame(['duolingo'], $duolingo['validated_targets']);
        $this->assertNotNull($etoro);
        $this->assertSame(4, $etoro['validated_level']);
        $this->assertSame(['yoniassia'], $etoro['validated_targets']);
        $this->assertSame(4, $flickr['validated_level']);
        $this->assertSame(['flickr'], $flickr['validated_targets']);
        $this->assertNotNull($freesound);
        $this->assertSame(3, $freesound['validated_level']);
        $this->assertSame(['freesound'], $freesound['validated_targets']);
        $this->assertSame(4, $freelancer['validated_level']);
        $this->assertSame(['freelancer'], $freelancer['validated_targets']);
        $this->assertSame(4, $github['level']);
        $this->assertSame('profile-html-enrichment', $github['strategy']);
        $this->assertSame(4, $github['validated_level']);
        $this->assertSame(4, $ghostForum['validated_level']);
        $this->assertSame(['ghost'], $ghostForum['validated_targets']);
        $this->assertSame(4, $gitea['validated_level']);
        $this->assertSame(['lunny'], $gitea['validated_targets']);
        $this->assertSame(4, $githubgist['validated_level']);
        $this->assertSame(['sindresorhus'], $githubgist['validated_targets']);
        $this->assertSame(4, $gitlab['validated_level']);
        $this->assertSame(['gitlab-bot'], $gitlab['validated_targets']);
        $this->assertSame(4, $gravatar['validated_level']);
        $this->assertSame(['gravatar'], $gravatar['validated_targets']);
        $this->assertSame(4, $gumroad['validated_level']);
        $this->assertSame(['gumroad'], $gumroad['validated_targets']);
        $this->assertSame(3, $gpodderNet['validated_level']);
        $this->assertSame(['gpodder'], $gpodderNet['validated_targets']);
        $this->assertSame(4, $hackerrank['validated_level']);
        $this->assertSame(['hackerrank'], $hackerrank['validated_targets']);
        $this->assertSame(4, $habr['validated_level']);
        $this->assertSame(['habr'], $habr['validated_targets']);
        $this->assertSame(4, $hashicorpDiscuss['validated_level']);
        $this->assertSame(['apparentlymart'], $hashicorpDiscuss['validated_targets']);
        $this->assertSame(4, $hackernews['validated_level']);
        $this->assertContains('pg', $hackernews['validated_targets']);
        $this->assertSame(4, $hashnode['validated_level']);
        $this->assertSame(['hashnode'], $hashnode['validated_targets']);
        $this->assertSame(4, $huggingface['validated_level']);
        $this->assertSame(['openai'], $huggingface['validated_targets']);
        $this->assertSame(4, $imgur['validated_level']);
        $this->assertSame(['sarah'], $imgur['validated_targets']);
        $this->assertSame(4, $instructables['validated_level']);
        $this->assertSame(['instructables'], $instructables['validated_targets']);
        $this->assertSame(4, $ifttt['validated_level']);
        $this->assertSame(['ifttt'], $ifttt['validated_targets']);
        $this->assertSame(4, $itchIo['validated_level']);
        $this->assertSame(['itchio'], $itchIo['validated_targets']);
        $this->assertSame(4, $jupyterForum['validated_level']);
        $this->assertSame(['bollwyvl'], $jupyterForum['validated_targets']);
        $this->assertContains('torvalds', $github['validated_targets']);
        $this->assertGreaterThanOrEqual(3, $etsy['level']);
        $this->assertSame(4, $etsy['validated_level']);
        $this->assertSame(['andrew.brumbelow@gmail.com'], $etsy['validated_targets']);
        $this->assertGreaterThanOrEqual(3, $vivinoEmail['level']);
        $this->assertSame(3, $vivinoEmail['validated_level']);
        $this->assertSame(['hienyimba@gmail.com'], $vivinoEmail['validated_targets']);
        $this->assertSame(4, $kaggle['validated_level']);
        $this->assertSame(['serigne'], $kaggle['validated_targets']);
        $this->assertSame(4, $keybase['validated_level']);
        $this->assertContains('hynek', $keybase['validated_targets']);
        $this->assertSame(4, $kotlinDiscuss['validated_level']);
        $this->assertSame(['hhariri'], $kotlinDiscuss['validated_targets']);
        $this->assertSame(4, $leetcode['validated_level']);
        $this->assertSame(['leetcode'], $leetcode['validated_targets']);
        $this->assertSame(4, $lichess['validated_level']);
        $this->assertSame(['thibault'], $lichess['validated_targets']);
        $this->assertSame(4, $linktree['validated_level']);
        $this->assertContains('garyvee', $linktree['validated_targets']);
        $this->assertSame(4, $launchpad['validated_level']);
        $this->assertContains('mpt', $launchpad['validated_targets']);
        $this->assertSame(4, $lastfm['validated_level']);
        $this->assertSame(['wadecastle'], $lastfm['validated_targets']);
        $this->assertSame(4, $livejournal['validated_level']);
        $this->assertSame(['livejournal'], $livejournal['validated_targets']);
        $this->assertSame(4, $mastodon['validated_level']);
        $this->assertSame(['mastodon'], $mastodon['validated_targets']);
        $this->assertNotNull($minds);
        $this->assertSame(4, $minecraft['validated_level']);
        $this->assertSame(['minecraft'], $minecraft['validated_targets']);
        $this->assertSame(2, $minds['validated_level']);
        $this->assertSame(['minds'], $minds['validated_targets']);
        $this->assertSame(4, $mixcloud['validated_level']);
        $this->assertSame(['mixcloud'], $mixcloud['validated_targets']);
        $this->assertNotNull($monkeytype);
        $this->assertSame(4, $monkeytype['validated_level']);
        $this->assertSame(['monkeytype'], $monkeytype['validated_targets']);
        $this->assertSame(4, $niftygateway['validated_level']);
        $this->assertSame(['niftygateway'], $niftygateway['validated_targets']);
        $this->assertNotNull($naturalnews);
        $this->assertSame(4, $naturalnews['validated_level']);
        $this->assertSame(['naturalnews'], $naturalnews['validated_targets']);
        $this->assertSame(4, $mozillaDiscourse['validated_level']);
        $this->assertSame(['pmac'], $mozillaDiscourse['validated_targets']);
        $this->assertSame(4, $omglol['validated_level']);
        $this->assertSame(['adam'], $omglol['validated_targets']);
        $this->assertSame(4, $operaforums['validated_level']);
        $this->assertSame(['operaforums'], $operaforums['validated_targets']);
        $this->assertSame(4, $osu['validated_level']);
        $this->assertSame(['peppy'], $osu['validated_targets']);
        $this->assertSame(4, $openstreetmap['validated_level']);
        $this->assertSame(['SomeoneElse'], $openstreetmap['validated_targets']);
        $this->assertSame(4, $patreon['validated_level']);
        $this->assertSame(['patreon'], $patreon['validated_targets']);
        $this->assertSame(4, $pinterest['validated_level']);
        $this->assertSame(['pinterest'], $pinterest['validated_targets']);
        $this->assertGreaterThanOrEqual(2, $wix['level']);
        $this->assertSame(3, $packagist['validated_level']);
        $this->assertSame(['fabpot'], $packagist['validated_targets']);
        $this->assertSame(4, $paragraph['validated_level']);
        $this->assertSame(['paragraph'], $paragraph['validated_targets']);
        $this->assertSame(4, $pastebin['validated_level']);
        $this->assertSame(['ubuntu'], $pastebin['validated_targets']);
        $this->assertSame(4, $picsart['validated_level']);
        $this->assertSame(['picsart'], $picsart['validated_targets']);
        $this->assertNotNull($pypi);
        $this->assertSame(4, $pypi['validated_level']);
        $this->assertSame(['mitsuhiko'], $pypi['validated_targets']);
        $this->assertSame(4, $pythonDiscuss['validated_level']);
        $this->assertSame(['vstinner'], $pythonDiscuss['validated_targets']);
        $this->assertSame(3, $rubygems['validated_level']);
        $this->assertSame(['rails'], $rubygems['validated_targets']);
        $this->assertSame(4, $rustUsers['validated_level']);
        $this->assertSame(['nikomatsakis'], $rustUsers['validated_targets']);
        $this->assertSame(4, $scratch['validated_level']);
        $this->assertSame(['scratchteam'], $scratch['validated_targets']);
        $this->assertSame(4, $snapchat['validated_level']);
        $this->assertSame(['statedept'], $snapchat['validated_targets']);
        $this->assertSame(4, $sourceforge['validated_level']);
        $this->assertSame(['csc'], $sourceforge['validated_targets']);
        $this->assertSame(3, $stackoverflow['validated_level']);
        $this->assertSame(['jon-skeet'], $stackoverflow['validated_targets']);
        $this->assertNotNull($sportstracker);
        $this->assertSame(4, $sportstracker['validated_level']);
        $this->assertSame(['sportstracker'], $sportstracker['validated_targets']);
        $this->assertSame(4, $speedrun['validated_level']);
        $this->assertSame(['darbian'], $speedrun['validated_targets']);
        $this->assertSame(4, $statsfm['validated_level']);
        $this->assertSame(['statsfm'], $statsfm['validated_targets']);
        $this->assertSame(4, $steam['validated_level']);
        $this->assertSame(['steam'], $steam['validated_targets']);
        $this->assertSame(4, $soundcloud['validated_level']);
        $this->assertSame(['soundcloud'], $soundcloud['validated_targets']);
        $this->assertSame(4, $spotify['validated_level']);
        $this->assertSame(['spotify'], $spotify['validated_targets']);
        $this->assertSame(4, $substack['validated_level']);
        $this->assertContains('lennysnewsletter', $substack['validated_targets']);
        $this->assertSame(4, $telegram['validated_level']);
        $this->assertSame(['durov'], $telegram['validated_targets']);
        $this->assertSame(4, $trello['validated_level']);
        $this->assertSame(['trello'], $trello['validated_targets']);
        $this->assertSame(4, $vimeo['validated_level']);
        $this->assertSame(['staff'], $vimeo['validated_targets']);
        $this->assertSame(4, $vivino['validated_level']);
        $this->assertSame(['vivino'], $vivino['validated_targets']);
        $this->assertSame(4, $warpcast['validated_level']);
        $this->assertSame(['dwr'], $warpcast['validated_targets']);
        $this->assertNotNull($warframemarket);
        $this->assertSame(4, $warframemarket['validated_level']);
        $this->assertSame(['warframemarket'], $warframemarket['validated_targets']);
        $this->assertSame(4, $weebly['validated_level']);
        $this->assertSame(['weebly'], $weebly['validated_targets']);
        $this->assertSame(3, $wikipedia['validated_level']);
        $this->assertContains('Jimbo_Wales', $wikipedia['validated_targets']);
        $this->assertSame(4, $wordpress['validated_level']);
        $this->assertContains('dd32', $wordpress['validated_targets']);
        $this->assertSame(4, $x['validated_level']);
        $this->assertSame(['openai'], $x['validated_targets']);
        $this->assertSame(4, $youtube['validated_level']);
        $this->assertSame(['openai'], $youtube['validated_targets']);
    }
}
